### ISSUE TITLE
onSelect is fired on init and when the count is changed

### ISSUE THREAD

**Issue by fenech** [infusion/jQuery-Paging#15]
My `onSelect` handler uses AJAX to retrieve items. When I initialise the pagination, the contents of page 1 are already on the screen, so I don't want `onSelect` to fire on init and retrieve the same data again. At the moment I am dealing with this by using underscore.js `after` - `onSelect: _.after(2, myHandler)` but it would be better if the event simply didn't fire on init.

On a related note, the `onSelect` event is being fired whenever I change the number of items to be paginated. In my application I have a series of filters that can be applied to the the paged data. Of course, applying these filters changes the count. I have to do 2 separate requests, one to obtain the relevant items and the other to obtain the total number of items. Once I have the new number, I call `setNumber(newCount).setPage()` on my paging object. This fires the `onSelect` event, which requests the same data all over again.

Is there a way to prevent `onSelect` from being fired in these two circumstances?

**Comment by jatmew** [comment]
Hi,

I have run into this infinite loop issue when I simply want to do to redirect with the onSelect method. Reading above I see that this gets call on init() and probably why I am stuck in an infinite loop. For example my onSelect is the following function:

function (page) { window.location.replace(url+page) }

where url is path to a page. As you can see since the default page has this code on it, then it will infinitely loop. Any help will be appreciated.

James

**Comment by jatmew** [comment]
I figure out a solution, which was to check the complete window.location.href variable in order to determine whether the new url with the page parameter from onSelect function was the same as the current page href. If so, then it must have been an init of the page through some other method outside of clicking the pagination plugin.

**Comment by VerdonTrigance** [comment]
But it's not work when you use post ajax requests and window.location.href is same.
Anyway, I think we need additional option to fire or not to fire onSelect at init.

**Comment by infusion** [comment]
Could you please provide a jsfiddle or pastebin?

**Comment by VerdonTrigance** [comment]
I don't understand last question for me? Provide which part of what? Anyway, I have  resolved problem myself.
