### ISSUE TITLE
Example with Socket.io

### ISSUE THREAD

**Issue by aHumanBeing** [infusion/jQuery-Paging#16]
Hi,

I was excited to find this plugin today since I'm using socket.io with my web app.  Was wondering, would you have an example (server side) how this would look when using socket.io?  I plan to use this plugin to paginate results pulled from my database via socket.io

Thanks a bunch!

**Comment by infusion** [comment]
Hi, 

it depends on what you want to do with the paginator. I have an example for client-side code here: http://www.xarg.org/2011/09/jquery-pagination-revised/ on how to update the paginator as new data comes in.

For the server side, you could take the example code of the docs: http://socket.io/docs/

And emit like this:
socket.emit('pager', { number: 9818 }); // send new number of elements to the pager

**Comment by aHumanBeing** [comment]
Thanks for getting back!  I'm fine with a basic forward backward paginator to go through the results.  I have thousands of records and I'll display 10 records at a time.  I'll take a look into the example you provided.

**Comment by infusion** [comment]
And where comes socket.io into play? To paginate a big dataset it's as easy as using the slice-example on the page with jQuery. You get the offset-parameter for your database and put the result into the html-slice. I think updating the count of a paginator with a big dataset doesn't make sense, as most people don't go to the last page (or at least shouldn't be able to go to the end, as I wrote somewhere on my page, because of slow offset calculations in SQL).

**Comment by aHumanBeing** [comment]
It's not necessary that I use socket.io here.  I use it for other purposes in my app that I thought I may try it here as well.  You make a good point with regards to big data sets and the fact that most people don't go to the last page. I'll look at the slice-example.

**Comment by infusion** [comment]
I close that ticket for now. If you need further help, we can continue here.
